### ISSUE TITLE
Document improvement

### ISSUE THREAD

**Issue by basicmi** [alibaba/BladeDISC#86]
Hi,
At the end of [Abstract part of "A Walkthough of the BladeDISC Pass Pipeline"](https://alibaba.github.io/BladeDISC/docs/developers/pass_pipeline.html#abstract), it is mentioned, "We choose an input subgraph that contains as mush essential elements as possible to demo the pass pipeline.". Could you give more explanation of the input MLIR and why you choose this subgraph as an example?  
Thanks.

**Comment by linearhit** [comment]
We aim to provide a subgraph that is small enough but can demo the behavior of the passes as much as possible.
Specific for this subgraph, it contains the major elements including:
1, unknown dimensions in order to demo the whole flow of dynamic shape support, including the shape constraint analysis.
2, both fusion codegen lowering and library call support (compute-intensive part & memory-intensive part)
3, both shape calculation nodes & data calculation nodes from the input graph, to demo the placement passes and the consequent lowering of both host/device side. 
4, implicit broadcast semantics which need special treatment in dynamic shape support.

**Comment by basicmi** [comment]
got it. thanks
